name: checks
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Check style
        run: python3 -m ruff check . && python3 -m ruff format --check .
